### ISSUE TITLE
Evaluate Russian source for county level covid-19 data

### ISSUE THREAD

**Issue by asafary** [yahoo/covid-19-data#17]
Thanks for Artem Utkin for providing info on a possible new source for Russian case number
https://covid19.rosminzdrav.ru/

- [X] official primary source (government agency)
- [X] fills in missing data
- [X] data is updated regularly
- [X] data license

**Comment by artemoons** [comment]
It was really pleasant to help!
For others: the API itself is on this URL: https://covid19.rosminzdrav.ru/wp-json/api/mapdata/.

**Comment by ask4amit** [comment]
More details from @artemoons 

> Artem Utkin  8:33 PM
Thank you for response! BTW I'm still searching for API from https://xn--80aesfpebagmfblc0a.xn--p1ai/ (which is https://стопкоронавирус.рф/) :)
I got some success, found a request that return results for region, you just need to specify region code: https://стопкоронавирус.рф/covid_data.json?do=region_stats&code=RU-MOW (this one for Moscow, other codes are present for lookup in previous API).
okay, it's just some notes...

**Comment by asafary** [comment]
Russian subregion extraction has been setup including backfill
Will come out with larger subregion change included in:
#18
