### ISSUE TITLE
Prince George county, MD not being pulled

### ISSUE THREAD

**Issue by bcpugh** [yahoo/covid-19-data#20]
Prince George county (MD) is one of the largest COVID-19 case count regions in the mid Atlantic (larger than DC!) but it’s not showing up in the dataset.  I’m not sure how the data set is being pulled, but this data is available from the existing source https://coronavirus.maryland.gov/. It’s already included in the meta data definition tab, so maybe it’s a reasonable fix?

Let me know if I can help, thank you for this fantastic project.

**Comment by asafary** [comment]
Thank you for updating us!
We found an encoding issue in mapping the entries.

The data for the county should be available in a day (May 13th)

**Comment by asafary** [comment]
Prince George County is available in the dataset

**latest**
```json
{
  "regionId": "Prince_George%27s_County,_Maryland",
  "label": "Prince George's County, Maryland",
  "referenceDate": "2020-05-12",
  "lastUpdatedDate": null,
  "totalDeaths": 355,
  "totalConfirmedCases": 9892,
  "totalRecoveredCases": null,
  "totalTestedCases": null,
  "dataSource": "https://coronavirus.maryland.gov/"
}
```
**daily** (May 11th 2020)
```json
{
  "regionId": "Prince_George%27s_County,_Maryland",
  "label": "Prince George's County, Maryland",
  "referenceDate": "2020-05-11",
  "lastUpdatedDate": null,
  "totalDeaths": 342,
  "totalConfirmedCases": 9687,
  "totalRecoveredCases": null,
  "totalTestedCases": null,
  "numPositiveTests": 191,
  "numDeaths": 5,
  "numRecoveredCases": null,
  "diffNumPositiveTests": -100,
  "diffNumDeaths": 1,
  "avgWeeklyDeaths": 10.14,
  "avgWeeklyConfirmedCases": 298.43,
  "avgWeeklyRecoveredCases": null,
  "dataSource": "https://coronavirus.maryland.gov/"
}
```

**Comment by bcpugh** [comment]
Thank you! 

Can you give us an example query? I did an mvn clean install but I’m not getting any results with this query:

localhost:8080/api/json/v1/healthRecords?filter[healthRecords.wikiId]=="Prince_George%27s_County,_Maryland"&page[size]=3000

This is our last barrier to having a streamlined / automated analysis. Thank you so much!

**Comment by Chandrasekar-Rajasekar** [comment]
`http://localhost:8080/api/json/v1/healthRecords?filter[healthRecords]=wikiId=="Prince_George%2527s_County,_Maryland"&page[size]=3000`
The above query serves your purpose for now.

**Comment by asafary** [comment]
@bcpugh if you have any questions regarding to development or using the API please feel free to use the slack channel (link in the readme) as well
