### ISSUE TITLE
Statewide case/death chart sorts states with over a million cases at the bottom

### ISSUE THREAD

**Issue by shunting65** [yahoo/covid-19-data#30]
In the BY THE NUMBERS chart, cases by state are sorted with the most cases at the top, unless that state has over a million cases, in which they are listed at the bottom with the lower numbers.

**Comment by asafary** [comment]
Thank you for your feedback.
This repository is for maintaining the data itself and its correctness.

your comment regarding the UI in the Yahoo News will be forwarded to the relevant parties
