### ISSUE TITLE
Table of States by Virus Case Numbers

### ISSUE THREAD

**Issue by TCtheRogue** [yahoo/covid-19-data#31]
The 3 highest States in case numbers are always at the bottom of the list. I have read through the linked details but cannot find a reason. This has been reported in this fashion for a while. Thank you,
Terra Muma-Currier
terra.currier@gmail.com

**Comment by asafary** [comment]
Thank you Terra for your comment.
This repository is for maintaining the covid-19 data and its correctness, I have forwarded you comment to the Yahoo News team.
